# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellclock < Formula
  desc "Terminal UI time tracker — projects, tasks, and timed sessions in your terminal"
  homepage "https://github.com/jasonsoprovich/shellclock"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jasonsoprovich/shellclock/releases/download/v0.1.0/shellclock_Darwin_x86_64.tar.gz"
      sha256 "16b1466fd49a784a7ecee2d0006e76601eef92e40b969b3428e89a8fb296209f"

      define_method(:install) do
        bin.install "shellclock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jasonsoprovich/shellclock/releases/download/v0.1.0/shellclock_Darwin_arm64.tar.gz"
      sha256 "f269df34c78661ec89100ec3fabd66b9adb54e2fadc0b7c5ca5eea26e3ca1e37"

      define_method(:install) do
        bin.install "shellclock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jasonsoprovich/shellclock/releases/download/v0.1.0/shellclock_Linux_x86_64.tar.gz"
      sha256 "037a2d04fbc100b261f3263b5d56afdfac65c0461589dc51ffffec770382eadd"
      define_method(:install) do
        bin.install "shellclock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jasonsoprovich/shellclock/releases/download/v0.1.0/shellclock_Linux_arm64.tar.gz"
      sha256 "bc3f8575c115d15e9af6081c6f16b9093857c05eebdc5fe1212dc95d72242327"
      define_method(:install) do
        bin.install "shellclock"
      end
    end
  end
end
