# This file was generated by GoReleaser. DO NOT EDIT.
cask "shellclock" do
  name "shellclock"
  desc "Terminal UI time tracker — projects, tasks, and timed sessions in your terminal"
  homepage "https://github.com/jasonsoprovich/shellclock"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shellclock"

  on_macos do
    on_intel do
      url "https://github.com/jasonsoprovich/shellclock/releases/download/v#{version}/shellclock_Darwin_x86_64.tar.gz"
      sha256 "3b1833723a96958449b58c38f319e1284e78301b4a113c1c7444c9f37e426bda"
    end
    on_arm do
      url "https://github.com/jasonsoprovich/shellclock/releases/download/v#{version}/shellclock_Darwin_arm64.tar.gz"
      sha256 "3dcbfab5cdb30d674427d247d7b21bdd77bc83515bd2df872582628975ecf574"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jasonsoprovich/shellclock/releases/download/v#{version}/shellclock_Linux_x86_64.tar.gz"
      sha256 "415cd56be602cf82218c424d0d60891a67b418ce77f3135561bc3fe2244f82a4"
    end
    on_arm do
      url "https://github.com/jasonsoprovich/shellclock/releases/download/v#{version}/shellclock_Linux_arm64.tar.gz"
      sha256 "8c102e5b857bc9f16a2dcf8ba6f5500c1845922484a7dd3c42031e08574ddd23"
    end
  end

  # No zap stanza required
end
